version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    reviewers:
      - Nikita-Smirnov-Exactpro
      - OptimumCode
    labels:
      - dependencies
    schedule:
      interval: daily
    ignore:
      - versions:
        - "*-SNAPSHOT"
  - package-ecosystem: github-actions
    directory: /
    reviewers:
      - Nikita-Smirnov-Exactpro
      - OptimumCode
    labels:
      - dependencies
    schedule:
      interval: daily