version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    reviewers:
      - Nikita-Smirnov-Exactpro
    labels:
      - dependencies
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    reviewers:
      - Nikita-Smirnov-Exactpro
    labels:
      - dependencies
    schedule:
      interval: daily