version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    reviewers:
      - Nikita-Smirnov-Exactpro
      - OptimumCode
    labels:
      - dependencies
    schedule:
      interval: daily
    allow:
      - dependency-name: '*'
        dependency-type: production
  - package-ecosystem: github-actions
    directory: /
    reviewers:
      - Nikita-Smirnov-Exactpro
      - OptimumCode
    labels:
      - dependencies
    schedule:
      interval: daily